
  
  #include-once 
 #include <FileConstants.au3> 
 #include <Array.au3> 
 #include <MsgBoxConstants.au3> 
 #include <File.au3> 
 
 
; === Auto-Generated Include File (using _ArrayAdd) ===
Global $aBat1_Lines
$aBat1_Lines = '' 
_ArrayAdd($aBat1_Lines, '@@ECHO OFF')
_ArrayAdd($aBat1_Lines, 'set "prj=tst29"')
_ArrayAdd($aBat1_Lines, ':: set prj MUST in LINE 2 :: ws edit src prj-name-dir ::')
_ArrayAdd($aBat1_Lines, 'REM *** IMPORTANT: The first 3 lines (including "set prj=...") used by  external software it interacts with.')
_ArrayAdd($aBat1_Lines, 'rem !!!DO NOT CHANGE!!! ***')
_ArrayAdd($aBat1_Lines, 'REM *** only push . must exist: REPO, BARE-REPO und REMOTE  ***')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, 'SETLOCAL')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, 'rem --- Globale Konfiguration (ReadOnly) ---')
_ArrayAdd($aBat1_Lines, 'set "REPO_DIR=D:\ws\gitGit\source\workspaces\%prj%"')
_ArrayAdd($aBat1_Lines, 'set "BARE_DIR=D:\ws\gitGit\source\local-bare-repos\%prj%.git"')
_ArrayAdd($aBat1_Lines, 'set "BRANCH=main"')
_ArrayAdd($aBat1_Lines, 'set "REMOTE=origin"')
_ArrayAdd($aBat1_Lines, 'set "FOLDERS=EDsrc"')
_ArrayAdd($aBat1_Lines, 'set "KEY_PATH=%USERPROFILE%\.ssh\id_ed25519"')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, 'REM Die vollstaendige URL wird nur zur Anzeige benoetigt, falls die Remote-Logik wieder aktiv wird.')
_ArrayAdd($aBat1_Lines, 'set "GITHUB_USER_URL=https://github.com/e6000000"')
_ArrayAdd($aBat1_Lines, 'set "FULL_REMOTE_URL=%GITHUB_USER_URL%/%prj%"')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, 'rem *** ENTFERNT: mkdir %REPO_DIR% und %BARE_DIR% ***')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, 'REM Check if a custom commit message was passed')
_ArrayAdd($aBat1_Lines, 'if "%COMMIT_MSG%"=="" (')
_ArrayAdd($aBat1_Lines, '    set "COMMIT_MSG=Auto-Commit %DATE% %TIME% see comments in file OLDCODE: NEWCODE: "')
_ArrayAdd($aBat1_Lines, ')')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, 'rem -------------------------------------------------------')
_ArrayAdd($aBat1_Lines, 'rem 1) TAG GENERATION WITH PSEUDO-VERSIONING (Code Block)')
_ArrayAdd($aBat1_Lines, 'rem -------------------------------------------------------')
_ArrayAdd($aBat1_Lines, 'set "YY=%DATE:~2,2%"')
_ArrayAdd($aBat1_Lines, 'set "MON=%DATE:~5,2%"')
_ArrayAdd($aBat1_Lines, 'set "DAY=%DATE:~8,2%"')
_ArrayAdd($aBat1_Lines, 'set "H=%TIME:~0,2%"')
_ArrayAdd($aBat1_Lines, 'if "%H:~0,1%"==" " set "H=0%H:~1,1%"')
_ArrayAdd($aBat1_Lines, 'set "MIN=%TIME:~3,2%"')
_ArrayAdd($aBat1_Lines, 'set "SEC=%TIME:~6,2%"')
_ArrayAdd($aBat1_Lines, 'set /a BASEYY=24')
_ArrayAdd($aBat1_Lines, 'set /a yearssince = YY - BASEYY')
_ArrayAdd($aBat1_Lines, 'if %yearssince% Lss 0 set /a yearssince=0')
_ArrayAdd($aBat1_Lines, 'set /a SEC_DAY=24*3600')
_ArrayAdd($aBat1_Lines, 'set /a SEC_MONTH=30*SEC_DAY')
_ArrayAdd($aBat1_Lines, 'set /a SEC_YEAR=360*SEC_DAY')
_ArrayAdd($aBat1_Lines, 'set /a mon = 1%MON% - 1')
_ArrayAdd($aBat1_Lines, 'set /a day = 1%DAY% - 1')
_ArrayAdd($aBat1_Lines, 'set /a hour = 1%H% - 1')
_ArrayAdd($aBat1_Lines, 'set /a minute = 1%MIN% - 1')
_ArrayAdd($aBat1_Lines, 'set /a second = 1%SEC% - 1')
_ArrayAdd($aBat1_Lines, 'set /a total = yearssince*SEC_YEAR + mon*SEC_MONTH + day*SEC_DAY + hour*3600 + minute*60 + second')
_ArrayAdd($aBat1_Lines, 'set /a step = (total / 2) %% 1000000000')
_ArrayAdd($aBat1_Lines, 'set /a step = step -162766300')
_ArrayAdd($aBat1_Lines, 'rem add /4 because it is ok no need tooo big numbers qq66yy')
_ArrayAdd($aBat1_Lines, 'set /a step = (step / 4)')
_ArrayAdd($aBat1_Lines, 'rem add /4 because it is ok no need tooo big numbers qq66yy')
_ArrayAdd($aBat1_Lines, 'set /a step = step + 1000000')
_ArrayAdd($aBat1_Lines, 'echo ver NR.')
_ArrayAdd($aBat1_Lines, 'echo %step%')
_ArrayAdd($aBat1_Lines, 'set "num=000000000%step%"')
_ArrayAdd($aBat1_Lines, 'set "num=%num:~-9%"')
_ArrayAdd($aBat1_Lines, 'set "version=datim_%num:~0,3%.%num:~3,3%.%num:~6,3%"')
_ArrayAdd($aBat1_Lines, 'echo version: %version%')
_ArrayAdd($aBat1_Lines, 'set "TAG_NAME=%version%"')
_ArrayAdd($aBat1_Lines, 'echo Generated Tag Name: %TAG_NAME%')
_ArrayAdd($aBat1_Lines, 'set "TAG_MSG_USER=[2033]"')
_ArrayAdd($aBat1_Lines, 'echo.')
_ArrayAdd($aBat1_Lines, 'set /p TAG_MSG_USER="Enter a Tag Message (Default: Release %TAG_NAME%): "')
_ArrayAdd($aBat1_Lines, 'if "%TAG_MSG_USER%"=="" (')
_ArrayAdd($aBat1_Lines, '    set "TAG_MSG_USER=Release %TAG_NAME%"')
_ArrayAdd($aBat1_Lines, ')')
_ArrayAdd($aBat1_Lines, 'echo _ _')
_ArrayAdd($aBat1_Lines, 'echo  _ prj: %prj%    _ branch: %branch%')
_ArrayAdd($aBat1_Lines, 'echo  _ TAG_MSG_USER: %TAG_MSG_USER%   _ TAG_NAME: %TAG_NAME%')
_ArrayAdd($aBat1_Lines, 'echo _ _')
_ArrayAdd($aBat1_Lines, 'rem -------------------------------------------------------')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, 'rem Change to Repo directory (Muss existieren!)')
_ArrayAdd($aBat1_Lines, 'cd /d "%REPO_DIR%"')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, 'rem (Optional) Set Git ssH-Command')
_ArrayAdd($aBat1_Lines, 'set "GIT_ssH_COMMAND=ssh -i "%KEY_PATH%" -o IdentitiesOnly=yes"')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, 'rem *** ENTFERNT: BARE REPO INITIALISIERUNG ***')
_ArrayAdd($aBat1_Lines, 'rem *** ENTFERNT: REPO INITIALISIERUNG (git init) ***')
_ArrayAdd($aBat1_Lines, 'rem *** ENTFERNT: BRANCH UMBENENNUNGS-LOGIK (da ''main'' nun Standard ist) ***')
_ArrayAdd($aBat1_Lines, 'rem *** ENTFERNT: REMOTE ADD/SET URL LOGIK (da ''origin'' nun existiert) ***')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, 'rem Add specified folders')
_ArrayAdd($aBat1_Lines, 'for %%F in (%FOLDERS%) do (')
_ArrayAdd($aBat1_Lines, '    echo git add "%%F"')
_ArrayAdd($aBat1_Lines, '    git add "%%F"')
_ArrayAdd($aBat1_Lines, ')')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, 'rem *** ENTFERNT: AUFRUF DER AutoIt EXE (nur fuer Erst-Erstellung) ***')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, 'rem Check if anything is staged, and CREATE COMMIT / TAG (Part 1)')
_ArrayAdd($aBat1_Lines, 'git diff --cached --quiet')
_ArrayAdd($aBat1_Lines, 'if errorlevel 1 (')
_ArrayAdd($aBat1_Lines, '    echo Changes are staged, creating Commit...')
_ArrayAdd($aBat1_Lines, '    git commit -m "%COMMIT_MSG%"')
_ArrayAdd($aBat1_Lines, '    if errorlevel 1 (')
_ArrayAdd($aBat1_Lines, '        echo Commit failed.')
_ArrayAdd($aBat1_Lines, '        timeout /t 222')
_ArrayAdd($aBat1_Lines, '        exit /b 1')
_ArrayAdd($aBat1_Lines, '    )')
_ArrayAdd($aBat1_Lines, '    echo Commit successful.')
_ArrayAdd($aBat1_Lines, '    echo.')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, '    rem Create tag with custom message')
_ArrayAdd($aBat1_Lines, '    echo  * creating Tag %TAG_NAME% with message "%TAG_MSG_USER%"...')
_ArrayAdd($aBat1_Lines, '    git tag -a "%TAG_NAME%" -m "%TAG_MSG_USER%"')
_ArrayAdd($aBat1_Lines, '    if errorlevel 1 (')
_ArrayAdd($aBat1_Lines, '        echo Tag creation failed.')
_ArrayAdd($aBat1_Lines, '        timeout /t 222')
_ArrayAdd($aBat1_Lines, '        exit /b 1')
_ArrayAdd($aBat1_Lines, '    )')
_ArrayAdd($aBat1_Lines, '    echo Tag %TAG_NAME% successfully created.')
_ArrayAdd($aBat1_Lines, '    echo.')
_ArrayAdd($aBat1_Lines, '    ')
_ArrayAdd($aBat1_Lines, '    rem #######################################################')
_ArrayAdd($aBat1_Lines, '    rem START: BARE-REPO PUSH (Part 1: Push to local Bare Repo)')
_ArrayAdd($aBat1_Lines, '    rem #######################################################')
_ArrayAdd($aBat1_Lines, '    echo WARNING: Now pushing to local Bare Repo %BARE_DIR%.')
_ArrayAdd($aBat1_Lines, '    if /I "y"=="y" (')
_ArrayAdd($aBat1_Lines, '        echo Pushing Branch %BRANCH% to %BARE_DIR% ...')
_ArrayAdd($aBat1_Lines, '        git push "%BARE_DIR%" %BRANCH%')
_ArrayAdd($aBat1_Lines, '        if errorlevel 1 (')
_ArrayAdd($aBat1_Lines, '            echo Push of Branch to BARE_DIR failed.')
_ArrayAdd($aBat1_Lines, '            timeout /t 222')
_ArrayAdd($aBat1_Lines, '            exit /b 1')
_ArrayAdd($aBat1_Lines, '        )')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, '        rem Push Tags')
_ArrayAdd($aBat1_Lines, '        echo Pushing Tag %TAG_NAME% to %BARE_DIR%...')
_ArrayAdd($aBat1_Lines, '        git push "%BARE_DIR%" "%TAG_NAME%"')
_ArrayAdd($aBat1_Lines, '        if errorlevel 1 (')
_ArrayAdd($aBat1_Lines, '            echo Push of Tag to BARE_DIR failed.')
_ArrayAdd($aBat1_Lines, '            timeout /t 222')
_ArrayAdd($aBat1_Lines, '            exit /b 1')
_ArrayAdd($aBat1_Lines, '        )')
_ArrayAdd($aBat1_Lines, '        ')
_ArrayAdd($aBat1_Lines, '        echo  ..')
_ArrayAdd($aBat1_Lines, '        echo ########################################    ')
_ArrayAdd($aBat1_Lines, '        echo Push and Tag Push to BARE_DIR %prj% successful.')
_ArrayAdd($aBat1_Lines, '        echo  .. ')
_ArrayAdd($aBat1_Lines, '         ')
_ArrayAdd($aBat1_Lines, '    ) else (')
_ArrayAdd($aBat1_Lines, '        echo BARE Push aborted.')
_ArrayAdd($aBat1_Lines, '    )')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, '    rem #######################################################')
_ArrayAdd($aBat1_Lines, '    rem START: REMOTE PUSH (Part 2: Push to external Remote %REMOTE%)')
_ArrayAdd($aBat1_Lines, '    rem *** AUSKOMMENTIERT: HIER ENDET DER BARE-REPO-TEIL ***')
_ArrayAdd($aBat1_Lines, '    rem #######################################################')
_ArrayAdd($aBat1_Lines, '    ')
_ArrayAdd($aBat1_Lines, '    rem echo.')
_ArrayAdd($aBat1_Lines, '    rem WARNING: In the next step, a force-push to REMOTE %REMOTE% will be executed.')
_ArrayAdd($aBat1_Lines, '    rem if /I "y"=="y" (')
_ArrayAdd($aBat1_Lines, '    rem     echo Pushing Branch %BRANCH% to %REMOTE% --force ...')
_ArrayAdd($aBat1_Lines, '    rem     git push %REMOTE% %BRANCH% --force')
_ArrayAdd($aBat1_Lines, '    rem     if errorlevel 1 (')
_ArrayAdd($aBat1_Lines, '    rem         echo Push of Branch to %REMOTE% failed.')
_ArrayAdd($aBat1_Lines, '    rem         timeout /t 222')
_ArrayAdd($aBat1_Lines, '    rem         exit /b 1')
_ArrayAdd($aBat1_Lines, '    rem     )')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, '    rem     rem Push Tags')
_ArrayAdd($aBat1_Lines, '    rem     echo Pushing Tag %TAG_NAME% to %REMOTE%...')
_ArrayAdd($aBat1_Lines, '    rem     git push %REMOTE% "%TAG_NAME%"')
_ArrayAdd($aBat1_Lines, '    rem     if errorlevel 1 (')
_ArrayAdd($aBat1_Lines, '    rem         echo Push of Tag to %REMOTE% failed.')
_ArrayAdd($aBat1_Lines, '    rem         timeout /t 222')
_ArrayAdd($aBat1_Lines, '    rem         exit /b 1')
_ArrayAdd($aBat1_Lines, '    rem     )')
_ArrayAdd($aBat1_Lines, '      ')
_ArrayAdd($aBat1_Lines, '    rem     echo  ..')
_ArrayAdd($aBat1_Lines, '    rem     echo ########################################    ')
_ArrayAdd($aBat1_Lines, '    rem     echo Force-push and Tag Push %prj% to github REMOTE %REMOTE% successful.')
_ArrayAdd($aBat1_Lines, '    rem     echo  .. ')
_ArrayAdd($aBat1_Lines, '    ')
_ArrayAdd($aBat1_Lines, '    ')
_ArrayAdd($aBat1_Lines, '    rem ) else (')
_ArrayAdd($aBat1_Lines, '    rem     echo REMOTE Push aborted. No push executed.')
_ArrayAdd($aBat1_Lines, '    rem )')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, ') else (')
_ArrayAdd($aBat1_Lines, '    echo No changes to commit.')
_ArrayAdd($aBat1_Lines, ')')
_ArrayAdd($aBat1_Lines, '')
_ArrayAdd($aBat1_Lines, ':ENDE')
_ArrayAdd($aBat1_Lines, 'timeout /t 222')
_ArrayAdd($aBat1_Lines, 'ENDLOCAL')
_ArrayAdd($aBat1_Lines, 'exit /b 0')

; === End of Auto-Generated Include File (using _ArrayAdd) ===
; === Auto-Generated Include File (using _ArrayAdd) ===
Global $aBat2_Lines
$aBat2_Lines = '' 
_ArrayAdd($aBat2_Lines, '@@ECHO OFF')
_ArrayAdd($aBat2_Lines, 'set "prj=tst29"')
_ArrayAdd($aBat2_Lines, ':: set prj MUST in LINE 2 :: ws edit src prj-name-dir ::')
_ArrayAdd($aBat2_Lines, 'REM *** IMPORTANT: The first 3 lines (including "set prj=...") used by  external software it interacts with.')
_ArrayAdd($aBat2_Lines, 'rem !!!DO NOT CHANGE!!! ***')
_ArrayAdd($aBat2_Lines, 'REM *** only push . must exist: REPO, BARE-REPO und REMOTE  ***')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, 'SETLOCAL')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, 'rem --- Globale Konfiguration (ReadOnly) ---')
_ArrayAdd($aBat2_Lines, 'set "REPO_DIR=D:\ws\gitGit\source\workspaces\%prj%"')
_ArrayAdd($aBat2_Lines, 'set "BARE_DIR=D:\ws\gitGit\source\local-bare-repos\%prj%.git"')
_ArrayAdd($aBat2_Lines, 'set "BRANCH=main"')
_ArrayAdd($aBat2_Lines, 'set "REMOTE=origin"')
_ArrayAdd($aBat2_Lines, 'set "FOLDERS=EDsrc"')
_ArrayAdd($aBat2_Lines, 'set "KEY_PATH=%USERPROFILE%\.ssh\id_ed25519"')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, 'REM Die vollstaendige URL wird nur zur Anzeige benoetigt, falls die Remote-Logik wieder aktiv wird.')
_ArrayAdd($aBat2_Lines, 'set "GITHUB_USER_URL=https://github.com/e6000000"')
_ArrayAdd($aBat2_Lines, 'set "FULL_REMOTE_URL=%GITHUB_USER_URL%/%prj%"')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, 'rem *** ENTFERNT: mkdir %REPO_DIR% und %BARE_DIR% ***')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, 'REM Check if a custom commit message was passed')
_ArrayAdd($aBat2_Lines, 'if "%COMMIT_MSG%"=="" (')
_ArrayAdd($aBat2_Lines, '    set "COMMIT_MSG=Auto-Commit %DATE% %TIME% see comments in file OLDCODE: NEWCODE: "')
_ArrayAdd($aBat2_Lines, ')')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, 'rem -------------------------------------------------------')
_ArrayAdd($aBat2_Lines, 'rem 1) TAG GENERATION WITH PSEUDO-VERSIONING (Code Block)')
_ArrayAdd($aBat2_Lines, 'rem -------------------------------------------------------')
_ArrayAdd($aBat2_Lines, 'set "YY=%DATE:~2,2%"')
_ArrayAdd($aBat2_Lines, 'set "MON=%DATE:~5,2%"')
_ArrayAdd($aBat2_Lines, 'set "DAY=%DATE:~8,2%"')
_ArrayAdd($aBat2_Lines, 'set "H=%TIME:~0,2%"')
_ArrayAdd($aBat2_Lines, 'if "%H:~0,1%"==" " set "H=0%H:~1,1%"')
_ArrayAdd($aBat2_Lines, 'set "MIN=%TIME:~3,2%"')
_ArrayAdd($aBat2_Lines, 'set "SEC=%TIME:~6,2%"')
_ArrayAdd($aBat2_Lines, 'set /a BASEYY=24')
_ArrayAdd($aBat2_Lines, 'set /a yearssince = YY - BASEYY')
_ArrayAdd($aBat2_Lines, 'if %yearssince% Lss 0 set /a yearssince=0')
_ArrayAdd($aBat2_Lines, 'set /a SEC_DAY=24*3600')
_ArrayAdd($aBat2_Lines, 'set /a SEC_MONTH=30*SEC_DAY')
_ArrayAdd($aBat2_Lines, 'set /a SEC_YEAR=360*SEC_DAY')
_ArrayAdd($aBat2_Lines, 'set /a mon = 1%MON% - 1')
_ArrayAdd($aBat2_Lines, 'set /a day = 1%DAY% - 1')
_ArrayAdd($aBat2_Lines, 'set /a hour = 1%H% - 1')
_ArrayAdd($aBat2_Lines, 'set /a minute = 1%MIN% - 1')
_ArrayAdd($aBat2_Lines, 'set /a second = 1%SEC% - 1')
_ArrayAdd($aBat2_Lines, 'set /a total = yearssince*SEC_YEAR + mon*SEC_MONTH + day*SEC_DAY + hour*3600 + minute*60 + second')
_ArrayAdd($aBat2_Lines, 'set /a step = (total / 2) %% 1000000000')
_ArrayAdd($aBat1_Lines, 'set /a step = step -162766300')
_ArrayAdd($aBat1_Lines, 'rem add /4 because it is ok no need tooo big numbers qq66yy')
_ArrayAdd($aBat1_Lines, 'set /a step = (step / 4)')
_ArrayAdd($aBat1_Lines, 'rem add /4 because it is ok no need tooo big numbers qq66yy')
_ArrayAdd($aBat2_Lines, 'set /a step = step + 1000000')
_ArrayAdd($aBat2_Lines, 'echo ver NR.')
_ArrayAdd($aBat2_Lines, 'echo %step%')
_ArrayAdd($aBat2_Lines, 'set "num=000000000%step%"')
_ArrayAdd($aBat2_Lines, 'set "num=%num:~-9%"')
_ArrayAdd($aBat2_Lines, 'set "version=datim_%num:~0,3%.%num:~3,3%.%num:~6,3%"')
_ArrayAdd($aBat2_Lines, 'echo version: %version%')
_ArrayAdd($aBat2_Lines, 'set "TAG_NAME=%version%"')
_ArrayAdd($aBat2_Lines, 'echo Generated Tag Name: %TAG_NAME%')
_ArrayAdd($aBat2_Lines, 'set "TAG_MSG_USER=[2033]"')
_ArrayAdd($aBat2_Lines, 'echo.')
_ArrayAdd($aBat2_Lines, 'set /p TAG_MSG_USER="Enter a Tag Message (Default: Release %TAG_NAME%): "')
_ArrayAdd($aBat2_Lines, 'if "%TAG_MSG_USER%"=="" (')
_ArrayAdd($aBat2_Lines, '    set "TAG_MSG_USER=Release %TAG_NAME%"')
_ArrayAdd($aBat2_Lines, ')')
_ArrayAdd($aBat2_Lines, 'echo _ _')
_ArrayAdd($aBat2_Lines, 'echo  _ prj: %prj%    _ branch: %branch%')
_ArrayAdd($aBat2_Lines, 'echo  _ TAG_MSG_USER: %TAG_MSG_USER%   _ TAG_NAME: %TAG_NAME%')
_ArrayAdd($aBat2_Lines, 'echo _ _')
_ArrayAdd($aBat2_Lines, 'rem -------------------------------------------------------')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, 'rem Change to Repo directory (Muss existieren!)')
_ArrayAdd($aBat2_Lines, 'cd /d "%REPO_DIR%"')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, 'rem (Optional) Set Git ssH-Command')
_ArrayAdd($aBat2_Lines, 'set "GIT_ssH_COMMAND=ssh -i "%KEY_PATH%" -o IdentitiesOnly=yes"')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, 'rem *** ENTFERNT: BARE REPO INITIALISIERUNG ***')
_ArrayAdd($aBat2_Lines, 'rem *** ENTFERNT: REPO INITIALISIERUNG (git init) ***')
_ArrayAdd($aBat2_Lines, 'rem *** ENTFERNT: BRANCH UMBENENNUNGS-LOGIK (da ''main'' nun Standard ist) ***')
_ArrayAdd($aBat2_Lines, 'rem *** ENTFERNT: REMOTE ADD/SET URL LOGIK (da ''origin'' nun existiert) ***')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, 'rem Add specified folders')
_ArrayAdd($aBat2_Lines, 'for %%F in (%FOLDERS%) do (')
_ArrayAdd($aBat2_Lines, '    echo git add "%%F"')
_ArrayAdd($aBat2_Lines, '    git add "%%F"')
_ArrayAdd($aBat2_Lines, ')')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, 'rem *** ENTFERNT: AUFRUF DER AutoIt EXE (nur fuer Erst-Erstellung) ***')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, 'rem Check if anything is staged, and CREATE COMMIT / TAG (Part 1)')
_ArrayAdd($aBat2_Lines, 'git diff --cached --quiet')
_ArrayAdd($aBat2_Lines, 'if errorlevel 1 (')
_ArrayAdd($aBat2_Lines, '    echo Changes are staged, creating Commit...')
_ArrayAdd($aBat2_Lines, '    git commit -m "%COMMIT_MSG%"')
_ArrayAdd($aBat2_Lines, '    if errorlevel 1 (')
_ArrayAdd($aBat2_Lines, '        echo Commit failed.')
_ArrayAdd($aBat2_Lines, '        timeout /t 222')
_ArrayAdd($aBat2_Lines, '        exit /b 1')
_ArrayAdd($aBat2_Lines, '    )')
_ArrayAdd($aBat2_Lines, '    echo Commit successful.')
_ArrayAdd($aBat2_Lines, '    echo.')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, '    rem Create tag with custom message')
_ArrayAdd($aBat2_Lines, '    echo  * creating Tag %TAG_NAME% with message "%TAG_MSG_USER%"...')
_ArrayAdd($aBat2_Lines, '    git tag -a "%TAG_NAME%" -m "%TAG_MSG_USER%"')
_ArrayAdd($aBat2_Lines, '    if errorlevel 1 (')
_ArrayAdd($aBat2_Lines, '        echo Tag creation failed.')
_ArrayAdd($aBat2_Lines, '        timeout /t 222')
_ArrayAdd($aBat2_Lines, '        exit /b 1')
_ArrayAdd($aBat2_Lines, '    )')
_ArrayAdd($aBat2_Lines, '    echo Tag %TAG_NAME% successfully created.')
_ArrayAdd($aBat2_Lines, '    echo.')
_ArrayAdd($aBat2_Lines, '    ')
_ArrayAdd($aBat2_Lines, '    rem #######################################################')
_ArrayAdd($aBat2_Lines, '    rem START: BARE-REPO PUSH (Part 1: Push to local Bare Repo)')
_ArrayAdd($aBat2_Lines, '    rem *** AUSKOMMENTIERT: HIER BEGINNT DER BARE-REPO-TEIL ***')
_ArrayAdd($aBat2_Lines, '    rem #######################################################')
_ArrayAdd($aBat2_Lines, '    ')
_ArrayAdd($aBat2_Lines, '    rem echo WARNING: Now pushing to local Bare Repo %BARE_DIR%.')
_ArrayAdd($aBat2_Lines, '    rem if /I "y"=="y" (')
_ArrayAdd($aBat2_Lines, '    rem     echo Pushing Branch %BRANCH% to %BARE_DIR% ...')
_ArrayAdd($aBat2_Lines, '    rem     git push "%BARE_DIR%" %BRANCH%')
_ArrayAdd($aBat2_Lines, '    rem     if errorlevel 1 (')
_ArrayAdd($aBat2_Lines, '    rem         echo Push of Branch to BARE_DIR failed.')
_ArrayAdd($aBat2_Lines, '    rem         timeout /t 222')
_ArrayAdd($aBat2_Lines, '    rem         exit /b 1')
_ArrayAdd($aBat2_Lines, '    rem     )')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, '    rem     rem Push Tags')
_ArrayAdd($aBat2_Lines, '    rem     echo Pushing Tag %TAG_NAME% to %BARE_DIR%...')
_ArrayAdd($aBat2_Lines, '    rem     git push "%BARE_DIR%" "%TAG_NAME%"')
_ArrayAdd($aBat2_Lines, '    rem     if errorlevel 1 (')
_ArrayAdd($aBat2_Lines, '    rem         echo Push of Tag to BARE_DIR failed.')
_ArrayAdd($aBat2_Lines, '    rem         timeout /t 222')
_ArrayAdd($aBat2_Lines, '    rem         exit /b 1')
_ArrayAdd($aBat2_Lines, '    rem     )')
_ArrayAdd($aBat2_Lines, '        ')
_ArrayAdd($aBat2_Lines, '    rem     echo  ..')
_ArrayAdd($aBat2_Lines, '    rem     echo ########################################    ')
_ArrayAdd($aBat2_Lines, '    rem     echo Push and Tag Push to BARE_DIR %prj% successful.')
_ArrayAdd($aBat2_Lines, '    rem     echo  .. ')
_ArrayAdd($aBat2_Lines, '         ')
_ArrayAdd($aBat2_Lines, '    rem ) else (')
_ArrayAdd($aBat2_Lines, '    rem     echo BARE Push aborted.')
_ArrayAdd($aBat2_Lines, '    rem )')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, '    rem #######################################################')
_ArrayAdd($aBat2_Lines, '    rem START: REMOTE PUSH (Part 2: Push to external Remote %REMOTE%)')
_ArrayAdd($aBat2_Lines, '    rem #######################################################')
_ArrayAdd($aBat2_Lines, '    echo.')
_ArrayAdd($aBat2_Lines, '    echo WARNING: In the next step, a force-push to REMOTE %REMOTE% will be executed.')
_ArrayAdd($aBat2_Lines, '    if /I "y"=="y" (')
_ArrayAdd($aBat2_Lines, '        echo Pushing Branch %BRANCH% to %REMOTE% --force ...')
_ArrayAdd($aBat2_Lines, '        git push %REMOTE% %BRANCH% --force')
_ArrayAdd($aBat2_Lines, '        if errorlevel 1 (')
_ArrayAdd($aBat2_Lines, '            echo Push of Branch to %REMOTE% failed.')
_ArrayAdd($aBat2_Lines, '            timeout /t 222')
_ArrayAdd($aBat2_Lines, '            exit /b 1')
_ArrayAdd($aBat2_Lines, '        )')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, '        rem Push Tags')
_ArrayAdd($aBat2_Lines, '        echo Pushing Tag %TAG_NAME% to %REMOTE%...')
_ArrayAdd($aBat2_Lines, '        git push %REMOTE% "%TAG_NAME%"')
_ArrayAdd($aBat2_Lines, '        if errorlevel 1 (')
_ArrayAdd($aBat2_Lines, '            echo Push of Tag to %REMOTE% failed.')
_ArrayAdd($aBat2_Lines, '            timeout /t 222')
_ArrayAdd($aBat2_Lines, '            exit /b 1')
_ArrayAdd($aBat2_Lines, '        )')
_ArrayAdd($aBat2_Lines, '      ')
_ArrayAdd($aBat2_Lines, '        echo  ..')
_ArrayAdd($aBat2_Lines, '        echo ########################################    ')
_ArrayAdd($aBat2_Lines, '        echo Force-push and Tag Push %prj% to github REMOTE %REMOTE% successful.')
_ArrayAdd($aBat2_Lines, '        echo  .. ')
_ArrayAdd($aBat2_Lines, '    ')
_ArrayAdd($aBat2_Lines, '    ')
_ArrayAdd($aBat2_Lines, '    ) else (')
_ArrayAdd($aBat2_Lines, '        echo REMOTE Push aborted. No push executed.')
_ArrayAdd($aBat2_Lines, '    )')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, ') else (')
_ArrayAdd($aBat2_Lines, '    echo No changes to commit.')
_ArrayAdd($aBat2_Lines, ')')
_ArrayAdd($aBat2_Lines, '')
_ArrayAdd($aBat2_Lines, ':ENDE')
_ArrayAdd($aBat2_Lines, 'timeout /t 222')
_ArrayAdd($aBat2_Lines, 'ENDLOCAL')
_ArrayAdd($aBat2_Lines, 'exit /b 0')

; === End of Auto-Generated Include File (using _ArrayAdd) ===
; === Auto-Generated Include File (using _ArrayAdd) ===
Global $aBat3_Lines
$aBat3_Lines = '' 
_ArrayAdd($aBat3_Lines, '@@ECHO OFF')
_ArrayAdd($aBat3_Lines, 'set "prj=tst29"')
_ArrayAdd($aBat3_Lines, ':: set prj MUST in LINE 2 :: ws edit src prj-name-dir ::')
_ArrayAdd($aBat3_Lines, 'REM *** IMPORTANT: The first 3 lines (including "set prj=...") used by  external software it interacts with.')
_ArrayAdd($aBat3_Lines, 'rem !!!DO NOT CHANGE!!! ***')
_ArrayAdd($aBat3_Lines, 'REM *** WICHTIG: Ueberschreibt den Workspace komplett mit der NEUESTEN BARE-REPO Version! ***')
_ArrayAdd($aBat3_Lines, 'REM *** Es setzt voraus, dass REPO und BARE-REPO existieren. ***')
_ArrayAdd($aBat3_Lines, '')
_ArrayAdd($aBat3_Lines, 'SETLOCAL')
_ArrayAdd($aBat3_Lines, '')
_ArrayAdd($aBat3_Lines, 'rem --- Globale Konfiguration (ReadOnly) ---')
_ArrayAdd($aBat3_Lines, 'set "REPO_DIR=D:\ws\gitGit\source\workspaces\%prj%"')
_ArrayAdd($aBat3_Lines, 'set "BARE_DIR=D:\ws\gitGit\source\local-bare-repos\%prj%.git"')
_ArrayAdd($aBat3_Lines, 'set "BRANCH=main"')
_ArrayAdd($aBat3_Lines, 'set "KEY_PATH=%USERPROFILE%\.ssh\id_ed25519"')
_ArrayAdd($aBat3_Lines, '')
_ArrayAdd($aBat3_Lines, 'rem Change to Repo directory (Muss existieren!)')
_ArrayAdd($aBat3_Lines, 'if not exist "%REPO_DIR%\" (')
_ArrayAdd($aBat3_Lines, '  echo Fehler: Repository directory "%REPO_DIR%" not found.')
_ArrayAdd($aBat3_Lines, '  timeout /t 222')
_ArrayAdd($aBat3_Lines, '  exit /b 1')
_ArrayAdd($aBat3_Lines, ')')
_ArrayAdd($aBat3_Lines, 'cd /d "%REPO_DIR%"')
_ArrayAdd($aBat3_Lines, '')
_ArrayAdd($aBat3_Lines, 'rem (Optional) Set Git SSH-Command')
_ArrayAdd($aBat3_Lines, 'set "GIT_SSH_COMMAND=ssh -i "%KEY_PATH%" -o IdentitiesOnly=yes"')
_ArrayAdd($aBat3_Lines, '')
_ArrayAdd($aBat3_Lines, 'echo  - -')
_ArrayAdd($aBat3_Lines, 'echo #######################################################')
_ArrayAdd($aBat3_Lines, 'echo START: BARE-REPO HARD PULL (Workspace Ueberschreiben - LATEST)')
_ArrayAdd($aBat3_Lines, 'echo #######################################################')
_ArrayAdd($aBat3_Lines, 'echo 1. Fetching latest changes from local BARE-REPO %BARE_DIR%...')
_ArrayAdd($aBat3_Lines, '')
_ArrayAdd($aBat3_Lines, 'rem *** 1. FETCH vom lokalen Bare-Repo (holt nur die Commits) ***')
_ArrayAdd($aBat3_Lines, 'git fetch "%BARE_DIR%" %BRANCH%')
_ArrayAdd($aBat3_Lines, 'if errorlevel 1 (')
_ArrayAdd($aBat3_Lines, '    echo Fehler beim Fetch vom BARE-REPO %BARE_DIR%.')
_ArrayAdd($aBat3_Lines, '    timeout /t 222')
_ArrayAdd($aBat3_Lines, '    exit /b 1')
_ArrayAdd($aBat3_Lines, ')')
_ArrayAdd($aBat3_Lines, 'echo Fetch vom BARE-REPO erfolgreich.')
_ArrayAdd($aBat3_Lines, '')
_ArrayAdd($aBat3_Lines, 'rem *** 2. HARD RESET auf den aktuellsten Stand des Bare-Repos (Ueberschreibt Workspace) ***')
_ArrayAdd($aBat3_Lines, 'echo 2. HARD RESET: Ueberschreibe Workspace mit der NEUESTEN Version (FETCH_HEAD)...')
_ArrayAdd($aBat3_Lines, 'rem FETCH_HEAD ist der Zeiger auf den letzten erfolgreich geholten Commit des Bare-Repos.')
_ArrayAdd($aBat3_Lines, 'git reset --hard FETCH_HEAD')
_ArrayAdd($aBat3_Lines, 'if errorlevel 1 (')
_ArrayAdd($aBat3_Lines, '    echo FATALER FEHLER: Hard Reset vom BARE-REPO fehlgeschlagen.')
_ArrayAdd($aBat3_Lines, '    timeout /t 222')
_ArrayAdd($aBat3_Lines, '    exit /b 1')
_ArrayAdd($aBat3_Lines, ')')
_ArrayAdd($aBat3_Lines, '')
_ArrayAdd($aBat3_Lines, 'echo  - -')
_ArrayAdd($aBat3_Lines, 'echo #######################################################')
_ArrayAdd($aBat3_Lines, 'echo Hard Reset (Ueberschreiben) erfolgreich.')
_ArrayAdd($aBat3_Lines, 'echo Workspace wurde mit neuestem Stand aus BARE-REPO synchronisiert.')
_ArrayAdd($aBat3_Lines, 'echo  - -')
_ArrayAdd($aBat3_Lines, ':ENDE')
_ArrayAdd($aBat3_Lines, 'timeout /t 222')
_ArrayAdd($aBat3_Lines, 'ENDLOCAL')
_ArrayAdd($aBat3_Lines, 'exit /b 0')

; === End of Auto-Generated Include File (using _ArrayAdd) ===
; === Auto-Generated Include File (using _ArrayAdd) ===
Global $aBat4_Lines
$aBat4_Lines = '' 
_ArrayAdd($aBat4_Lines, '@@ECHO OFF')
_ArrayAdd($aBat4_Lines, 'set "prj=tst29"')
_ArrayAdd($aBat4_Lines, ':: set prj MUST in LINE 2 :: ws edit src prj-name-dir ::')
_ArrayAdd($aBat4_Lines, 'REM *** IMPORTANT: The first 3 lines (including "set prj=...") used by  external software it interacts with.')
_ArrayAdd($aBat4_Lines, 'rem !!!DO NOT CHANGE!!! ***')
_ArrayAdd($aBat4_Lines, 'REM *** WICHTIG: Ueberschreibt den Workspace komplett mit der NEUESTEN GITHUB-Version! ***')
_ArrayAdd($aBat4_Lines, 'REM *** Es setzt voraus, dass REPO und REMOTE (origin) existieren. ***')
_ArrayAdd($aBat4_Lines, '')
_ArrayAdd($aBat4_Lines, 'SETLOCAL')
_ArrayAdd($aBat4_Lines, '')
_ArrayAdd($aBat4_Lines, 'rem --- Globale Konfiguration (ReadOnly) ---')
_ArrayAdd($aBat4_Lines, 'set "REPO_DIR=D:\ws\gitGit\source\workspaces\%prj%"')
_ArrayAdd($aBat4_Lines, 'set "BRANCH=main"')
_ArrayAdd($aBat4_Lines, 'set "REMOTE=origin"')
_ArrayAdd($aBat4_Lines, 'set "KEY_PATH=%USERPROFILE%\.ssh\id_ed25519"')
_ArrayAdd($aBat4_Lines, '')
_ArrayAdd($aBat4_Lines, 'rem Change to Repo directory (Muss existieren!)')
_ArrayAdd($aBat4_Lines, 'if not exist "%REPO_DIR%\" (')
_ArrayAdd($aBat4_Lines, '  echo Fehler: Repository directory "%REPO_DIR%" not found.')
_ArrayAdd($aBat4_Lines, '  timeout /t 222')
_ArrayAdd($aBat4_Lines, '  exit /b 1')
_ArrayAdd($aBat4_Lines, ')')
_ArrayAdd($aBat4_Lines, 'cd /d "%REPO_DIR%"')
_ArrayAdd($aBat4_Lines, '')
_ArrayAdd($aBat4_Lines, 'rem (Optional) Set Git SSH-Command')
_ArrayAdd($aBat4_Lines, 'set "GIT_SSH_COMMAND=ssh -i "%KEY_PATH%" -o IdentitiesOnly=yes"')
_ArrayAdd($aBat4_Lines, '')
_ArrayAdd($aBat4_Lines, 'echo  - -')
_ArrayAdd($aBat4_Lines, 'echo #######################################################')
_ArrayAdd($aBat4_Lines, 'echo START: GITHUB HARD PULL (Workspace Ueberschreiben - LATEST)')
_ArrayAdd($aBat4_Lines, 'echo #######################################################')
_ArrayAdd($aBat4_Lines, 'echo 1. Fetching latest changes from GITHUB REMOTE %REMOTE%...')
_ArrayAdd($aBat4_Lines, '')
_ArrayAdd($aBat4_Lines, 'rem *** 1. FETCH vom externen Remote (holt nur die Commits) ***')
_ArrayAdd($aBat4_Lines, 'git fetch %REMOTE% %BRANCH%')
_ArrayAdd($aBat4_Lines, 'if errorlevel 1 (')
_ArrayAdd($aBat4_Lines, '    echo Fehler beim Fetch vom REMOTE %REMOTE%.')
_ArrayAdd($aBat4_Lines, '    timeout /t 222')
_ArrayAdd($aBat4_Lines, '    exit /b 1')
_ArrayAdd($aBat4_Lines, ')')
_ArrayAdd($aBat4_Lines, 'echo Fetch vom REMOTE %REMOTE% erfolgreich.')
_ArrayAdd($aBat4_Lines, '')
_ArrayAdd($aBat4_Lines, 'rem *** 2. HARD RESET auf den aktuellsten Stand von origin/main (Ueberschreibt Workspace) ***')
_ArrayAdd($aBat4_Lines, 'echo 2. HARD RESET: Ueberschreibe Workspace mit der NEUESTEN Version (%REMOTE%/%BRANCH%)...')
_ArrayAdd($aBat4_Lines, 'rem Setzt den lokalen Branch auf den Stand des Remote-Tracking-Branches zurueck und verwirft alle Aenderungen.')
_ArrayAdd($aBat4_Lines, 'git reset --hard %REMOTE%/%BRANCH%')
_ArrayAdd($aBat4_Lines, 'if errorlevel 1 (')
_ArrayAdd($aBat4_Lines, '    echo FATALER FEHLER: Hard Reset vom REMOTE fehlgeschlagen.')
_ArrayAdd($aBat4_Lines, '    timeout /t 222')
_ArrayAdd($aBat4_Lines, '    exit /b 1')
_ArrayAdd($aBat4_Lines, ')')
_ArrayAdd($aBat4_Lines, '')
_ArrayAdd($aBat4_Lines, 'echo  - -')
_ArrayAdd($aBat4_Lines, 'echo #######################################################')
_ArrayAdd($aBat4_Lines, 'echo Hard Reset (Ueberschreiben) erfolgreich.')
_ArrayAdd($aBat4_Lines, 'echo Workspace wurde mit neuestem Stand von GITHUB synchronisiert.')
_ArrayAdd($aBat4_Lines, 'echo  - -')
_ArrayAdd($aBat4_Lines, ':ENDE')
_ArrayAdd($aBat4_Lines, 'timeout /t 222')
_ArrayAdd($aBat4_Lines, 'ENDLOCAL')
_ArrayAdd($aBat4_Lines, 'exit /b 0')

; === End of Auto-Generated Include File (using _ArrayAdd) ===
; === Auto-Generated Include File (using _ArrayAdd) ===
Global $aBat5_Lines
$aBat5_Lines = '' 
_ArrayAdd($aBat5_Lines, '@@ECHO OFF')
_ArrayAdd($aBat5_Lines, 'set "prj=tst29"')
_ArrayAdd($aBat5_Lines, ':: set prj MUST in LINE 2 :: ws edit src prj-name-dir ::')
_ArrayAdd($aBat5_Lines, 'REM *** IMPORTANT: The first 3 lines (including "set prj=...") used by  external software it interacts with.')
_ArrayAdd($aBat5_Lines, 'rem !!!DO NOT CHANGE!!! ***')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'SETLOCAL')
_ArrayAdd($aBat5_Lines, 'rem --- Global Configuration (set once) ---')
_ArrayAdd($aBat5_Lines, 'set "REPO_DIR=D:\ws\gitGit\source\workspaces\%prj%"')
_ArrayAdd($aBat5_Lines, 'set "BARE_DIR=D:\ws\gitGit\source\local-bare-repos\%prj%.git"')
_ArrayAdd($aBat5_Lines, 'set "BRANCH=main"')
_ArrayAdd($aBat5_Lines, 'set "REMOTE=origin"')
_ArrayAdd($aBat5_Lines, 'set "FOLDERS=EDsrc"')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'rem *** FIX #1: GITHUBURL wird als Basis-URL OHNE %prj% definiert, fuer die saubere Remote-Logik ***')
_ArrayAdd($aBat5_Lines, 'set "GITHUB_USER_URL=https://github.com/e6000000"')
_ArrayAdd($aBat5_Lines, 'set "FULL_REMOTE_URL=%GITHUB_USER_URL%/%prj%"')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'set "KEY_PATH=%USERPROFILE%\.ssh\id_ed25519" ')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'rem bevore gitpush copy gitPublic to 55My')
_ArrayAdd($aBat5_Lines, 'rem after gitFetch copy gitPriv to 55My')
_ArrayAdd($aBat5_Lines, 'mkdir  %REPO_DIR%\EDsrc\main\55My   2>nul ')
_ArrayAdd($aBat5_Lines, 'mkdir  %REPO_DIR%\EDsrc\gitPriv  2>nul ')
_ArrayAdd($aBat5_Lines, 'mkdir  %REPO_DIR%\EDsrc\gitPublic   2>nul ')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'mkdir  %BARE_DIR%       2>nul ')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'REM Check if a custom commit message was passed')
_ArrayAdd($aBat5_Lines, 'if "%COMMIT_MSG%"=="" (')
_ArrayAdd($aBat5_Lines, '    set "COMMIT_MSG=Auto-Commit %DATE% %TIME% see comments in file OLDCODE: NEWCODE: "')
_ArrayAdd($aBat5_Lines, ')')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'rem -------------------------------------------------------')
_ArrayAdd($aBat5_Lines, 'rem 1) TAG GENERATION WITH PSEUDO-VERSIONING (datim_YYMM.DDHH.MMSS)')
_ArrayAdd($aBat5_Lines, 'rem -------------------------------------------------------')
_ArrayAdd($aBat5_Lines, 'set "YY=%DATE:~2,2%"')
_ArrayAdd($aBat5_Lines, 'set "MON=%DATE:~5,2%"')
_ArrayAdd($aBat5_Lines, 'set "DAY=%DATE:~8,2%"')
_ArrayAdd($aBat5_Lines, 'set "H=%TIME:~0,2%"')
_ArrayAdd($aBat5_Lines, 'if "%H:~0,1%"==" " set "H=0%H:~1,1%"')
_ArrayAdd($aBat5_Lines, 'set "MIN=%TIME:~3,2%"')
_ArrayAdd($aBat5_Lines, 'set "SEC=%TIME:~6,2%"')
_ArrayAdd($aBat5_Lines, 'set /a BASEYY=24')
_ArrayAdd($aBat5_Lines, 'set /a yearsSince = YY - BASEYY')
_ArrayAdd($aBat5_Lines, 'if %yearsSince% LSS 0 set /a yearsSince=0')
_ArrayAdd($aBat5_Lines, 'set /a SEC_DAY=24*3600')
_ArrayAdd($aBat5_Lines, 'set /a SEC_MONTH=30*SEC_DAY')
_ArrayAdd($aBat5_Lines, 'set /a SEC_YEAR=360*SEC_DAY')
_ArrayAdd($aBat5_Lines, 'set /a mon = 1%MON% - 1')
_ArrayAdd($aBat5_Lines, 'set /a day = 1%DAY% - 1')
_ArrayAdd($aBat5_Lines, 'set /a hour = 1%H% - 1')
_ArrayAdd($aBat5_Lines, 'set /a minute = 1%MIN% - 1')
_ArrayAdd($aBat5_Lines, 'set /a second = 1%SEC% - 1')
_ArrayAdd($aBat5_Lines, 'set /a total = yearsSince*SEC_YEAR + mon*SEC_MONTH + day*SEC_DAY + hour*3600 + minute*60 + second')
_ArrayAdd($aBat5_Lines, 'set /a step = (total / 2) %% 1000000000')
_ArrayAdd($aBat1_Lines, 'set /a step = step -162766300')
_ArrayAdd($aBat1_Lines, 'rem add /4 because it is ok no need tooo big numbers qq66yy')
_ArrayAdd($aBat1_Lines, 'set /a step = (step / 4)')
_ArrayAdd($aBat1_Lines, 'rem add /4 because it is ok no need tooo big numbers qq66yy')
_ArrayAdd($aBat5_Lines, 'set /a step = step + 1000000')
_ArrayAdd($aBat5_Lines, 'echo ver NR.')
_ArrayAdd($aBat5_Lines, 'echo %step%')
_ArrayAdd($aBat5_Lines, 'set "num=000000000%step%"')
_ArrayAdd($aBat5_Lines, 'set "num=%num:~-9%"')
_ArrayAdd($aBat5_Lines, 'set "version=datim_%num:~0,3%.%num:~3,3%.%num:~6,3%"')
_ArrayAdd($aBat5_Lines, 'echo version: %version%')
_ArrayAdd($aBat5_Lines, 'set "TAG_NAME=%version%"')
_ArrayAdd($aBat5_Lines, 'echo Generated Tag Name: %TAG_NAME%')
_ArrayAdd($aBat5_Lines, 'set "TAG_MSG_USER=[2033]"')
_ArrayAdd($aBat5_Lines, 'echo.')
_ArrayAdd($aBat5_Lines, 'set /p TAG_MSG_USER="Enter a Tag Message (Default: Release %TAG_NAME%): "')
_ArrayAdd($aBat5_Lines, 'if "%TAG_MSG_USER%"=="" (')
_ArrayAdd($aBat5_Lines, '    set "TAG_MSG_USER=Release %TAG_NAME%"')
_ArrayAdd($aBat5_Lines, ')')
_ArrayAdd($aBat5_Lines, 'echo _ _')
_ArrayAdd($aBat5_Lines, 'echo  _ prj: %prj%    _ branch: %branch%')
_ArrayAdd($aBat5_Lines, 'echo  _ TAG_MSG_USER: %TAG_MSG_USER%   _ TAG_NAME: %TAG_NAME%')
_ArrayAdd($aBat5_Lines, 'echo _ _')
_ArrayAdd($aBat5_Lines, 'rem -------------------------------------------------------')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'rem Change to Repo directory')
_ArrayAdd($aBat5_Lines, 'if not exist "%REPO_DIR%\" (')
_ArrayAdd($aBat5_Lines, '  echo Repository directory "%REPO_DIR%" not found.')
_ArrayAdd($aBat5_Lines, '  timeout /t 222')
_ArrayAdd($aBat5_Lines, '  exit /b 1')
_ArrayAdd($aBat5_Lines, ')')
_ArrayAdd($aBat5_Lines, 'cd /d "%REPO_DIR%"')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'rem (Optional) Set Git SSH-Command')
_ArrayAdd($aBat5_Lines, 'set "GIT_SSH_COMMAND=ssh -i "%KEY_PATH%" -o IdentitiesOnly=yes"')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'rem #######################################################')
_ArrayAdd($aBat5_Lines, 'rem NEW: 3) CREATE BARE REPO IF NOT PRESENT')
_ArrayAdd($aBat5_Lines, 'rem #######################################################')
_ArrayAdd($aBat5_Lines, 'if not exist "%BARE_DIR%\" (')
_ArrayAdd($aBat5_Lines, '  echo.')
_ArrayAdd($aBat5_Lines, '  echo LOCAL BARE REPO "%BARE_DIR%" NOT FOUND.')
_ArrayAdd($aBat5_Lines, '  set "BARE_CREATE="')
_ArrayAdd($aBat5_Lines, '  if /I "y"=="y" (')
_ArrayAdd($aBat5_Lines, '    echo Creating Bare Repo in "%BARE_DIR%"...')
_ArrayAdd($aBat5_Lines, '    git init --bare "%BARE_DIR%"')
_ArrayAdd($aBat5_Lines, '    if errorlevel 1 (')
_ArrayAdd($aBat5_Lines, '      echo Bare Repo creation failed.')
_ArrayAdd($aBat5_Lines, '      timeout /t 222')
_ArrayAdd($aBat5_Lines, '      exit /b 1')
_ArrayAdd($aBat5_Lines, '    )')
_ArrayAdd($aBat5_Lines, '    echo Bare Repo successfully created.')
_ArrayAdd($aBat5_Lines, '  ) else (')
_ArrayAdd($aBat5_Lines, '    echo Bare Repo creation skipped.')
_ArrayAdd($aBat5_Lines, '  )')
_ArrayAdd($aBat5_Lines, ')')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'rem #######################################################')
_ArrayAdd($aBat5_Lines, 'rem NEW: 4) INITIALIZE ws REPO IF NOT PRESENT')
_ArrayAdd($aBat5_Lines, 'rem #######################################################')
_ArrayAdd($aBat5_Lines, 'git rev-parse --git-dir >nul 2>&1')
_ArrayAdd($aBat5_Lines, 'if errorlevel 1 (')
_ArrayAdd($aBat5_Lines, '  echo.')
_ArrayAdd($aBat5_Lines, '  echo Not a Git Repository in "%REPO_DIR%".')
_ArrayAdd($aBat5_Lines, '  if /I "y"=="y" (')
_ArrayAdd($aBat5_Lines, '    echo Initializing Repository with git init...')
_ArrayAdd($aBat5_Lines, '    ')
_ArrayAdd($aBat5_Lines, '    rem *** FIX: Stelle sicher, dass der initiale Branch ''main'' ist ***')
_ArrayAdd($aBat5_Lines, '    git config init.defaultBranch main ')
_ArrayAdd($aBat5_Lines, '    ')
_ArrayAdd($aBat5_Lines, '    git init')
_ArrayAdd($aBat5_Lines, '    if errorlevel 1 (')
_ArrayAdd($aBat5_Lines, '      echo Initialization failed.')
_ArrayAdd($aBat5_Lines, '      timeout /t 222')
_ArrayAdd($aBat5_Lines, '      exit /b 1')
_ArrayAdd($aBat5_Lines, '    )')
_ArrayAdd($aBat5_Lines, '    echo Repository successfully initialized.')
_ArrayAdd($aBat5_Lines, '  ) else (')
_ArrayAdd($aBat5_Lines, '    echo Initialization skipped. Script will exit.')
_ArrayAdd($aBat5_Lines, '    timeout /t 222')
_ArrayAdd($aBat5_Lines, '    exit /b 1')
_ArrayAdd($aBat5_Lines, '  )')
_ArrayAdd($aBat5_Lines, ')')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'rem #######################################################')
_ArrayAdd($aBat5_Lines, 'rem FIX: Ensure BRANCH is set to ''main'' (Nur fuer Repos, die noch master haben)')
_ArrayAdd($aBat5_Lines, 'rem #######################################################')
_ArrayAdd($aBat5_Lines, 'git symbolic-ref --short HEAD | findstr /I /C:"master" >nul 2>&1')
_ArrayAdd($aBat5_Lines, 'if not errorlevel 1 (')
_ArrayAdd($aBat5_Lines, '  git branch -m master main')
_ArrayAdd($aBat5_Lines, '  echo Renamed initial branch ''master'' to ''main''.')
_ArrayAdd($aBat5_Lines, ') else (')
_ArrayAdd($aBat5_Lines, '  git checkout %BRANCH% 2>nul')
_ArrayAdd($aBat5_Lines, ')')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'rem #######################################################')
_ArrayAdd($aBat5_Lines, 'rem FIX #2: KORREKTE REMOTE-LOGIK (Add ODER Set-URL)')
_ArrayAdd($aBat5_Lines, 'rem #######################################################')
_ArrayAdd($aBat5_Lines, 'echo Ensuring Remote ''%REMOTE%'' points to: %FULL_REMOTE_URL%')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'git remote add %REMOTE% %FULL_REMOTE_URL% 2>nul')
_ArrayAdd($aBat5_Lines, 'if errorlevel 1 (')
_ArrayAdd($aBat5_Lines, '  rem Remote existiert bereits. Setze die URL neu (FIX fuer die unvollstaendige URL)')
_ArrayAdd($aBat5_Lines, '  git remote set-url %REMOTE% %FULL_REMOTE_URL%')
_ArrayAdd($aBat5_Lines, '  echo Remote origin URL successfully updated to: %FULL_REMOTE_URL%')
_ArrayAdd($aBat5_Lines, ') else (')
_ArrayAdd($aBat5_Lines, '  echo Remote origin successfully added.')
_ArrayAdd($aBat5_Lines, ')')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'rem Add specified folders')
_ArrayAdd($aBat5_Lines, 'for %%F in (%FOLDERS%) do (')
_ArrayAdd($aBat5_Lines, '  if exist "%%F" (')
_ArrayAdd($aBat5_Lines, '    echo git add "%%F"')
_ArrayAdd($aBat5_Lines, '    git add "%%F"')
_ArrayAdd($aBat5_Lines, '  ) else (')
_ArrayAdd($aBat5_Lines, '    echo Folder "%%F" does not exist - skipping.')
_ArrayAdd($aBat5_Lines, '  )')
_ArrayAdd($aBat5_Lines, ')')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'rem check exist und call AutoIt EXE')
_ArrayAdd($aBat5_Lines, 'ECHO Rufe 5gitwebNEWprj.exe mit dem Parameter "%prj%" auf und warte...')
_ArrayAdd($aBat5_Lines, 'START /WAIT "" "D:\ws\gitGit\5gitwebNEWprj.exe" "%prj%"')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'IF ERRORLEVEL 1 (')
_ArrayAdd($aBat5_Lines, '    ECHO Fehler: 5gitwebNEWprj.exe wurde mit einem Fehlercode beendet.')
_ArrayAdd($aBat5_Lines, '    GOTO :ENDE')
_ArrayAdd($aBat5_Lines, ') ELSE (')
_ArrayAdd($aBat5_Lines, '    ECHO 5gitwebNEWprj.exe erfolgreich beendet.')
_ArrayAdd($aBat5_Lines, ')')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, 'rem Check if anything is staged, and CREATE COMMIT / TAG (Part 1)')
_ArrayAdd($aBat5_Lines, 'git diff --cached --quiet')
_ArrayAdd($aBat5_Lines, 'if errorlevel 1 (')
_ArrayAdd($aBat5_Lines, '  echo Changes are staged, creating Commit...')
_ArrayAdd($aBat5_Lines, '  git commit -m "%COMMIT_MSG%"')
_ArrayAdd($aBat5_Lines, '  if errorlevel 1 (')
_ArrayAdd($aBat5_Lines, '    echo Commit failed.')
_ArrayAdd($aBat5_Lines, '    timeout /t 222')
_ArrayAdd($aBat5_Lines, '    exit /b 1')
_ArrayAdd($aBat5_Lines, '  )')
_ArrayAdd($aBat5_Lines, '  echo Commit successful.')
_ArrayAdd($aBat5_Lines, '  echo.')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, '  rem Create tag with custom message')
_ArrayAdd($aBat5_Lines, '  echo  * creating Tag %TAG_NAME% with message "%TAG_MSG_USER%"...')
_ArrayAdd($aBat5_Lines, '  git tag -a "%TAG_NAME%" -m "%TAG_MSG_USER%"')
_ArrayAdd($aBat5_Lines, '  if errorlevel 1 (')
_ArrayAdd($aBat5_Lines, '    echo Tag creation failed.')
_ArrayAdd($aBat5_Lines, '    timeout /t 222')
_ArrayAdd($aBat5_Lines, '    exit /b 1')
_ArrayAdd($aBat5_Lines, '  )')
_ArrayAdd($aBat5_Lines, '  echo Tag %TAG_NAME% successfully created.')
_ArrayAdd($aBat5_Lines, '  echo.')
_ArrayAdd($aBat5_Lines, '  ')
_ArrayAdd($aBat5_Lines, '  rem #######################################################')
_ArrayAdd($aBat5_Lines, '  rem START: BARE-REPO PUSH (Part 1: Push to local Bare Repo)')
_ArrayAdd($aBat5_Lines, '  rem #######################################################')
_ArrayAdd($aBat5_Lines, '  echo WARNING: Now pushing to local Bare Repo %BARE_DIR%.')
_ArrayAdd($aBat5_Lines, '  if /I "y"=="y" (')
_ArrayAdd($aBat5_Lines, '    echo Pushing Branch %BRANCH% to %BARE_DIR% ...')
_ArrayAdd($aBat5_Lines, '    git push "%BARE_DIR%" %BRANCH%')
_ArrayAdd($aBat5_Lines, '    if errorlevel 1 (')
_ArrayAdd($aBat5_Lines, '      echo Push of Branch to BARE_DIR failed.')
_ArrayAdd($aBat5_Lines, '      timeout /t 222')
_ArrayAdd($aBat5_Lines, '      exit /b 1')
_ArrayAdd($aBat5_Lines, '    )')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, '    rem Push Tags')
_ArrayAdd($aBat5_Lines, '    echo Pushing Tag %TAG_NAME% to %BARE_DIR%...')
_ArrayAdd($aBat5_Lines, '    git push "%BARE_DIR%" "%TAG_NAME%"')
_ArrayAdd($aBat5_Lines, '    if errorlevel 1 (')
_ArrayAdd($aBat5_Lines, '      echo Push of Tag to BARE_DIR failed.')
_ArrayAdd($aBat5_Lines, '      timeout /t 222')
_ArrayAdd($aBat5_Lines, '      exit /b 1')
_ArrayAdd($aBat5_Lines, '    )')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, '    echo  ..')
_ArrayAdd($aBat5_Lines, '    echo ########################################')
_ArrayAdd($aBat5_Lines, '    echo Push and Tag Push to BARE_DIR successful.')
_ArrayAdd($aBat5_Lines, '    echo  .. ')
_ArrayAdd($aBat5_Lines, '  ) else (')
_ArrayAdd($aBat5_Lines, '    echo BARE Push aborted.')
_ArrayAdd($aBat5_Lines, '  )')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, '  rem #######################################################')
_ArrayAdd($aBat5_Lines, '  rem START: REMOTE PUSH (Part 2: Push to external Remote %REMOTE%)')
_ArrayAdd($aBat5_Lines, '  rem #######################################################')
_ArrayAdd($aBat5_Lines, '  echo.')
_ArrayAdd($aBat5_Lines, '  echo WARNING: In the next step, a force-push to REMOTE %REMOTE% will be executed.')
_ArrayAdd($aBat5_Lines, '  if /I "y"=="y" (')
_ArrayAdd($aBat5_Lines, '    echo Pushing Branch %BRANCH% to %REMOTE% --force ...')
_ArrayAdd($aBat5_Lines, '    git push %REMOTE% %BRANCH% --force')
_ArrayAdd($aBat5_Lines, '    if errorlevel 1 (')
_ArrayAdd($aBat5_Lines, '      echo Push of Branch to %REMOTE% failed.')
_ArrayAdd($aBat5_Lines, '      timeout /t 222')
_ArrayAdd($aBat5_Lines, '      exit /b 1')
_ArrayAdd($aBat5_Lines, '    )')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, '    rem Push Tags')
_ArrayAdd($aBat5_Lines, '    echo Pushing Tag %TAG_NAME% to %REMOTE%...')
_ArrayAdd($aBat5_Lines, '    git push %REMOTE% "%TAG_NAME%"')
_ArrayAdd($aBat5_Lines, '    if errorlevel 1 (')
_ArrayAdd($aBat5_Lines, '      echo Push of Tag to %REMOTE% failed.')
_ArrayAdd($aBat5_Lines, '      timeout /t 222')
_ArrayAdd($aBat5_Lines, '      exit /b 1')
_ArrayAdd($aBat5_Lines, '    )')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, '    echo  ..')
_ArrayAdd($aBat5_Lines, '    echo ########################################')
_ArrayAdd($aBat5_Lines, '    echo Force-push and Tag Push to REMOTE %REMOTE% successful.')
_ArrayAdd($aBat5_Lines, '    echo  ..')
_ArrayAdd($aBat5_Lines, '  ) else (')
_ArrayAdd($aBat5_Lines, '    echo REMOTE Push aborted. No push executed.')
_ArrayAdd($aBat5_Lines, '  )')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, ') else (')
_ArrayAdd($aBat5_Lines, '  echo No changes to commit.')
_ArrayAdd($aBat5_Lines, ')')
_ArrayAdd($aBat5_Lines, '')
_ArrayAdd($aBat5_Lines, ':ENDE')
_ArrayAdd($aBat5_Lines, 'timeout /t 222')
_ArrayAdd($aBat5_Lines, 'ENDLOCAL')
_ArrayAdd($aBat5_Lines, 'exit /b 0')

; === End of Auto-Generated Include File (using _ArrayAdd) ===
